get:
  tags:
    - "users"
  security:
    - JWT: [ ]
  summary: "Find user by publicID"
  description: "Returns a single user"
  operationId: "getUserById"
  produces:
    - "application/json"
  parameters:
    - name: "public_id"
      in: "path"
      description: "ID of user to return"
      required: true
      type: "string"
  responses:
    "200":
      description: "successful operation"
      schema:
        $ref: "swagger-user-models.yaml#/User"